# Generated by Django 5.1.1 on 2024-10-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_customuser_is_admin"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="is_admin",),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
